# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'demo' do
   pod 'AFNetworking', '~> 3.1.0'
   	pod 'SDWebImage', '~> 3.8.1'
	pod 'YYWebImage'
   pod 'YYModel', '~> 1.0.4'
   pod 'MJExtension', '~> 3.0.13'


end

target 'demoTests' do

end

target 'demoUITests' do

end

